version: '2'
services:
    mongodb:
        restart: always
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_INITDB_DATABASE=poll
        volumes:
          - ./data/db:/data/db
        ports:
            - 9500:9500
        command: mongod --port 9500 --logpath=/dev/null  